services:
  api:
    image: axava-tech-lab/name_bot:latest
    build: .
    ports:
      - 8002:8002
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_HOME = /usr/local/cuda-12.4
